version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-
      - checkout
      - restore_cache:
          keys:
            - homebrew
      - run:
          name: Install Ant
          command: brew install ant
      - run:
          name: Build with Ant
          command: ant
      - run:
          name: Build with Buck
          command: ./bin/buck build --show-output buck
      - store_artifacts:
          path: buck-out/gen/programs/buck.pex
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - save_cache:
          key: homebrew
          paths:
            - "/usr/local/Homebrew"
